### ISSUE TITLE
Any preview yet?

### ISSUE THREAD

**Issue by Ladet02** [knyghty/django-admin-refresh#2]
The django admin definitely needs a refresh and easy customization. Thank you for taking this initiative.

do you have a preview as to what this might look like?

**Comment by knyghty** [comment]
Hi, thanks for the interest.

All current changes are on the `main` branch. I am off work most of this week so I will try to get a bit done, but my priority will be taking it easy.

I'm not a designer, so I haven't designed anything. I've just ripped out the current CSS and am rebuilding it as I go. I _hope_ that a designer will come along and help (e.g. we could probably use new icons?).

For now, the best you can do is check out the main branch, `pip install` the package locally, and add `admin_refresh` to the `INSTALLED_APPS` of an existing (or new) Django project.

I will try to make a pypi release soon, however, this is very early work, in fact I've barely made a start. So far I've only been working on the header and nav sidebar - everything else is just unstyled text, so there's not much to see yet.

PRs are welcome. I'm not sure where I would start as there's not much to go on. I hope to add some issues to the project soon with ideas / bugs / etc.

**Comment by Ladet02** [comment]
Brilliant, I'll do well to check it out as soon as I am off work today.

I'll also give some feedback as well.

Thank you.

**Comment by knyghty** [comment]
I've made an initial PyPI release and added docs to the readme, so I'm going to close this issue now.

However I'd be delighted to get feedback - I've added discussions to the project, so you can put any general feedback in there. If you find any bugs, please open another issue 👍🏻
